enum navStyles {
  'NAV_STYLE_ABOVE_HEADER',
  'NAV_STYLE_BELOW_HEADER',
  'NAV_STYLE_DARK_HORIZONTAL',
  'NAV_STYLE_DEFAULT_HORIZONTAL',
  'NAV_STYLE_INSIDE_HEADER_HORIZONTAL',
  'NAV_STYLE_FIXED',
  'NAV_STYLE_DRAWER',
  'NAV_STYLE_MINI_SIDEBAR',
  'NAV_STYLE_NO_HEADER_MINI_SIDEBAR',
  'NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR'
}
enum layoutTypes {
  'LAYOUT_TYPE_BOXED',
  'LAYOUT_TYPE_FRAMED',
  'LAYOUT_TYPE_FULL'
}
export type NavStyle = keyof typeof navStyles;
export type LayoutType = keyof typeof layoutTypes;
